.\" This document is in the public domain.
.\" vim: fdm=marker cms=.\\"\ %s
.
.\" FRONT MATTER {{{
.Dd Jan 20, 2015
.Os
.Dt GIT-PIMP 1
.
.Sh NAME
.Nm git-pimp
.Nd Code review or pull requests as patch email series
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Op Fl \-to Ar ADDR
.Op Fl \-cc Ar ADDR
.Op Fl n
.Op Fl o Ar DIR
.Ar BASE
.Ar HEAD
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
generates a series of MIME messages from a range of commits
denoted by
.Li ( Ar BASE , Ar HEAD ] ,
with a cover letter summarizing the range.
.Nm
lets the user edit the cover letter, then submits all messages to
.Xr git-mailz 1 .
.
.Ss Options
.Bl -tag -width "xxx"
.It Fl \-cc Ar ADDR
Include
.Ar ADDR
in the
.Li Cc:
header of generated messages.
Overrides the
.Li pimp.cc
configuration setting.
.It Fl n
Exit before invoking
.Xr git-mailz 1 ,
preserve generated messages.
.It Fl o Ar DIR , Fl \-output Ar DIR
Write files to
.Ar DIR
instead of default
.Ev $PWD .
.It Fl \-to Ar ADDR
Include
.Ar ADDR
in the
.Li To:
header of generated messages.
Overrides the
.Li pimp.to
configuration setting.
.El
.Ss Configuration
.Bd -literal
[pimp]
  to = ADDR
  cc = ADDR
  editor = EXE
  output = DIR
  subjecttag = TAG
.Ed
.Bl -tag -width "xxx"
.It pimp.cc
See
.Fl \-cc .
.It pimp.editor
.Va EXE
is run with all messages as arguments before they're handed over to
.Xr git-mailz 1 .
If
.Li pimp.editor
is empty,
.Nm
falls back to
.Ev $VISUAL
and
.Ev $EDITOR ,
in this order.
If all three are empty,
.Nm
aborts.
If
.Va EXE
exits
.Li >0 ,
.Nm
aborts.
.It pimp.output
See
.Fl \-output .
.It pimp.subjecttag
Prefix essage subjects with
.Li [ Va TAG ] .
.It pimp.to
See
.Fl \-to .
.El
.\" DESCRIPTION }}}
.\" ENVIRONMENT {{{
.Sh ENVIRONMENT
.Bl -tag -width "xxx"
.It Ev EDITOR , Ev VISUAL
Defaults for the
.Li pimp.editor
configuration setting.
.It Ev GIT_PIMP_CHATTY , Ev GIT_PIMP_DRYRUN
Development and testing aids.
.El
.Pp
.Nm
may be influenced by environment variables used by
the programs listed in
.Sx SEE ALSO ,
possibly others.
.\" ENVIRONMENT }}}
.\" FILES {{{
.Sh FILES
.Nm
uses
.Xr git-config 1
to retrieve configuration settings.
.\" FILES }}}
.\" EXIT STATUS {{{
.Sh EXIT STATUS
.Ex -std
.\" EXIT STATUS }}}
.\" EXAMPLES {{{
.\"Sh EXAMPLES
.\" EXAMPLES }}}
.\" .Sh DIAGNOSTICS
.\" SEE ALSO {{{
.Sh SEE ALSO
.Xr git 1 ,
.Xr git-format-patch 1 ,
.Xr git-mailz 1 ,
.Xr git-mantle 1 ,
.Xr zsh 1 .
.\" SEE ALSO }}}
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" AUTHORS {{{
.Sh AUTHORS
.An Roman Neuhauser Aq Mt neuhauser+git-pimp@sigpipe.cz
.Lk https://github.com/roman-neuhauser/git-pimp/
.\" AUTHORS }}}
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/roman-neuhauser/git-pimp/issues
.\" BUGS }}}
